title: Megha Katiyar # your name (or website title) here
logo: "/images/WomxnHeadshot-Megha-7237.jpg" # your photo (or logo) here




description:Megha Katiyar has excelled in the field of Data for over 4 years, with a rich experience spanning data analysis to advanced data science. Renowned for her ability to craft impactful systems and sophisticated dashboards, she consistently drives efficiency and delivers actionable insights that propel business decisions.
  <a href="https://www.linkedin.com/in/megha-katiyar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
