title: Megha Katiyar # your name (or website title) here
logo: "/images/MeghaKatiyar_Photo.jpg" # your photo (or logo) here




description: Recent masters graduate (masters in Computer Engineering) from University of Toronto with an experience of 2+ years in Software development and Machine Learning. Experience in Data Engineering and developing and operatonalizing Machine learning models usign Azure platform.

  
  <br><br>
  <a href="https://www.linkedin.com/in/megha-katiyar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
