title: Megha Katiyar # your name (or website title) here
logo: "/images/MeghaKatiyar_Photo.jpg" # your photo (or logo) here




description: I am an experienced data professional with over 4 years in the software industry. My expertise lies in transforming data into valuable insights that inspire informed decision making. I work with tools like ClicData and Tableau to create interactive dashboards that are highly engaging and informative. Python is my preferred programming language for data manipulation and automation.
  <a href="https://www.linkedin.com/in/megha-katiyar/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
